import jsPDF from "jspdf";
import type { Song } from "@/types/domain";

/**
 * Generate a PDF from a song with proper chord formatting.
 * Includes title, artist, body with chords and lyrics, and app source.
 */
export function generateSongPdf(song: Song) {
  const pdf = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 15;
  const lineHeight = 5;
  let yPosition = margin;

  // Helper to add text and track position
  const addText = (
    text: string,
    options: {
      size?: number;
      weight?: "normal" | "bold";
      align?: "left" | "center" | "right";
      maxWidth?: number;
    } = {}
  ) => {
    const { size = 12, weight = "normal", align = "left", maxWidth = pageWidth - margin * 2 } = options;
    pdf.setFontSize(size);
    pdf.setFont(undefined, weight === "bold" ? "bold" : "normal");

    const lines = pdf.splitTextToSize(text, maxWidth);
    lines.forEach((line: string) => {
      if (yPosition + lineHeight > pageHeight - margin) {
        pdf.addPage();
        yPosition = margin;
      }
      pdf.text(line, align === "center" ? pageWidth / 2 : margin, yPosition, {
        align,
        maxWidth,
      });
      yPosition += lineHeight;
    });
  };

  // Title
  if (song.title) {
    addText(song.title, { size: 18, weight: "bold" });
    yPosition += 2;
  }

  // Artist
  if (song.artist) {
    addText(`By ${song.artist}`, { size: 12 });
    yPosition += 3;
  }

  // Separator
  pdf.setDrawColor(150);
  pdf.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 5;

  // Body (chords and lyrics)
  if (song.body) {
    const bodyLines = song.body.split("\n");
    pdf.setFontSize(10);

    for (const line of bodyLines) {
      if (yPosition + lineHeight > pageHeight - margin) {
        pdf.addPage();
        yPosition = margin;
      }

      const trimmedLine = line.trim();

      // Handle section markers and comments
      if (trimmedLine.startsWith("{") || trimmedLine.startsWith("[")) {
        pdf.setFont(undefined, "bold");
        pdf.setTextColor(100, 100, 100);
        addText(trimmedLine, { size: 9 });
        pdf.setTextColor(0, 0, 0);
      } else if (trimmedLine) {
        // Regular content
        pdf.setFont(undefined, "normal");
        addText(trimmedLine, { size: 10 });
      } else {
        // Empty line
        yPosition += 2;
      }
    }
  }

  // Footer with app source
  yPosition = pageHeight - margin - 5;
  pdf.setFontSize(8);
  pdf.setFont(undefined, "normal");
  pdf.setTextColor(150, 150, 150);
  pdf.text(`Generated by Busk-O • Chords, lyrics & setlists for the stage`, pageWidth / 2, yPosition, {
    align: "center",
  });

  return pdf;
}

/**
 * Download a song as a PDF file.
 */
export function downloadSongPdf(song: Song) {
  const pdf = generateSongPdf(song);
  const filename = `${song.title || "song"}.pdf`.replace(/[^a-z0-9]/gi, "-").toLowerCase();
  pdf.save(filename);
}
